### ISSUE TITLE
update "Removing Legacy Trackers"

### ISSUE THREAD

**Issue by rozhkovets** [pnbruckner/ha-google-maps#16]
deleting (cleaning) file "known_devices.yaml" did not help me remove old devices.

this helped me

service: recorder.purge_entities
data:
  entity_globs: device_tracker.**_**_**_**_**_**
  domains: device_tracker
target:
  entity_id: null

https://community.home-assistant.io/t/how-to-remove-device-tracker-from-database/88775/16

**Comment by pnbruckner** [comment]
Well, removing known_devices.yaml and restarting HA _will_ remove the old tracker entities, although as you've seen, it doesn't remove their history. You can either purge that history manually, as you did, or just wait a week or so for it to automatically get purged. Bottom line, the issue is not removing the tracker entities, but rather their history.

Still, that's a good point and I'll add a note to the docs. Thanks!
