### ISSUE TITLE
Entity fails to load after system restart

### ISSUE THREAD

**Issue by prndlrm** [pnbruckner/ha-google-maps#25]
I am using integration version 1.3.1 but this happened in 1.3.0 also, not sure about prior versions. Home Assistant version 2024.3.1.

I am using the Personal + Alt account strategy. Upon a home assistant restart, the integration `devices` are present, but neither has an `entity`. If I simply reload the integration (for each account), the associated `entity` appears. I have not done extensive testing on this but in the last 15 minutes I restarted 6 times and it did this each time. Let me know if some kind of logs are needed to help diagnose this.

**Comment by pnbruckner** [comment]
When you say it had devices, but neither had entities, where exactly are you seeing that?

If you mean you're looking at the Google Maps Integration page under Settings -> Devices & services -> Google Maps, yes, that does sometimes happen. I don't know why. But it is a frontend/display issue with that page as far as I know. If you simply refresh the page (F5), the entities should appear. Also, if you look at the Developer tools -> STATES page, the entities will be there as well.

**Comment by prndlrm** [comment]
> If you mean you're looking at the Google Maps Integration page under Settings -> Devices & services -> Google Maps, yes, that does sometimes happen. I don't know why. But it is a frontend/display issue with that page as far as I know. If you simply refresh the page (F5), the entities should appear. Also, if you look at the Developer tools -> STATES page, the entities will be there as well.

Yes, Settings -> Devices & services -> Google Maps. It shows each of my google accounts and `1 device` underneath each. When I reload (using the 3-dot menu to the right of `CONFIGURE`) it changes to `1 device` and `1 entity` and all is good.

I just did it again, tried F5 as well as CTRL-F5 and got no change (I'm using chrome). In Developer tools -> STATES the entities do not show up until I do my reload exercise.

**Comment by pnbruckner** [comment]
Ok, got it. Well, I just looked at my test system, and yikes, it's doing the same thing for one of the two accounts! I happen to have some verbose debug logging on this system, and I can see it is clearly getting good data for the account that is showing no entities. Hmm...

Ok, I'll see what I can figure out. Thanks for letting me know!

**Comment by pnbruckner** [comment]
Do you know how to edit the code in the custom_components folder? I can suggest some logging to add which might help shed some light on what is happening. I added the additional logging to my test system, but after a restart it no longer experienced the problem. I've restarted several times, and it won't happen. Since you seem to be able to reproduce the problem with every restart, if you can add the logging, we might be able to diagnose the problem much more quickly.

**Comment by prndlrm** [comment]
I can edit files or replace files, whichever is fine. I just restarted and it did it again, so it does seem very reproducible for me at the moment.

**Comment by pnbruckner** [comment]
I have been able to reproduce the problem a few times, but not on every restart. So, I am able to try and diagnose the problem. I'll let you know if I need to take you up on the offer.

FWIW, so far, I can tell the data is being received, it's good, and the entity object(s) is/are getting created, but for some reason, they are not showing up. Something seems to be deleting them. I'll keep you posted.

**Comment by pnbruckner** [comment]
I think the problem is ultimately caused by some code in the device_tracker component level code that I've gotten bitten by before.

https://github.com/home-assistant/core/blob/51b8ffc69d2744f171e2132573bafabd0f8494c2/homeassistant/components/device_tracker/config_entry.py#L54-L74

It tries to delete devices associated with device trackers that were created by some older HA version (that apparently shouldn't have been created.) The problem is, there's a race condition, and it sometimes deletes the devices my integration has just created. (You can observe the effects in the Google Maps integration page where sometimes it shows entities but no devices. The opposite of the problem you're seeing. But if you refresh the page, the devices reappear.)

Anyway, when it does this it also somehow deletes the entities associated with the deleted devices. But, when you reload, or also often if you restart, everything goes back to normal. Since it is timing sensitive (being a race condition), sometimes it happens and sometimes it doesn't.

So, I need to find a better way to work around this stupid code (better than when I tried to work around it before.)

**Comment by pnbruckner** [comment]
The code mentioned above was added three years ago, with a comment that says it can be removed after 2022.6. Well, they apparently forgot about it.

I do see several standard integrations that have devices created for device_tracker entities. I'm guessing they are not getting bit by this problem because the also register other types of entities for the same device. The problematic code will only try to delete a device if it is associated with just a device_tracker entity and no other type of entity.

Rather than trying to get the old code removed, that was supposed to be removed a long time ago (I have no desire to try and fight that fight), I think I can work around this problem by registering another type of entity with each device, and register it as disabled. The downside is that for each person, there will be two entities, one device_tracker, which is wanted, and some other, disabled entity which is not wanted. I'm not sure there is any other way to guarantee the problem won't reoccur.

**Comment by prndlrm** [comment]
Interesting. Any possibility to create a disabled entity to get past the bad code that is trying to delete the device_tracker, then sometime after startup delete the disabled entity? A kludge for sure, but until the core code is cleaned up it probably has to be some kind of kludge.

**Comment by pnbruckner** [comment]
Actually, your question makes me realize it's a bigger problem because this can happen whenever ANY device tracker gets loaded. But I think I can create an entity that is both disabled and hidden. Hopefully, that will solve the problem.

**Comment by pnbruckner** [comment]
Update: As best I can tell, when the device_tracker component first tries to set up an integration's configuration entry, it will delete any devices that are only associated with device_tracker entities. In most cases, the integrations will simply recreate those devices and everything is fine.

I did an experiment where I created another entry in the entity registry for a different domain and also associated it with the device. This prevented the device_tracker component level code from deleting the device. However, even though the second entry was added disabled and hidden, it still shows up on the Google Maps integration page. For each device there is now two entities instead of one. I know this will confuse users, so I don't think is a reasonable workaround.

I think it might be possible that the entity (or entities) will reappear on its own if enough time goes by. To explain, a recent change in the implementation of the data update coordinator (that this and many other integrations use) can cause it to update the associated entities only if the data has changed. I recently used this new feature. So, if/when the data changes (i.e., the phone moves and there's new location data), it's possible the entity will update itself, causing the entity to reappear. I haven't tested this, but it's possible.

Even if I were to not use that new feature, there's still the basic problem of the device getting deleted in the first place. When this happens, it also deletes any associated entries from the entity registry. Even though in most cased both get recreated automatically, the mere fact of deleting the entity from the entity registry means that any changes the user has done (e.g., changing the entity ID, name, etc.) would be lost. That is not good and needs to be avoided.

Further testing seems to show that although in most cases, as described above, entries get recreated in both the device & entity registries, for some reason, sometimes the entity registry entry gets _removed_ instead of just being updated with the device info. I'm trying to figure out why this happens...

**Comment by gpion** [comment]
I subscribed to that thread because I'm experimenting the same issue (Settings -> Devices & services -> Google Maps sudenly show 4 devices but no entities) 
The difference is refreshing the page didn't fix it.
Restarting HA neither.

**Comment by pnbruckner** [comment]
That section of code in the device_tracker component level code that should have been removed a long time ago is making this a very difficult problem to solve. I've tried several work arounds, but none of them worked well in all cases. Unfortunately, it's very timing dependent, which means it also depends on what other device tracker integrations are being used, the random order they might get initialized, etc., etc.

However, I think I just figured out a work around that should resolve the problem. I'm testing now, and if it seems good, I'll release a beta with the fix (hopefully) soon.

**Comment by pnbruckner** [comment]
@prndlrm & @gpion, please try 1.3.2b0 and let me know if it resolves the problem for you.

**Comment by gpion** [comment]
> please try 1.3.2b0 and let me know if it resolves the problem for you.

I really do'nt know how I the update has worked 

I've clicked "add integration" button"from here https://github.com/pnbruckner/ha-google-maps/blob/1.3.2b0/README.md but dismissed the setup dialog

Anyway entities are back
BTW: how can I check which version is currently installed ?

**Comment by pnbruckner** [comment]
@gpion the ADD INTEGRATION button is what you would use to add (or "register") a Google Account with the integration. It is not how the integration is installed.

How did you install the integration in the first place? HACS? Manual? ...?

**Comment by gpion** [comment]
> How did you install the integration in the first place? HACS? Manual? ...?

HACS

**Comment by pnbruckner** [comment]
Then go to the HACS page, click on Google Maps, and it should show you which version is installed. You can also use the three-dot menu in the top-right to install a different version.

**Comment by gpion** [comment]
Oh sorry I used the direct download method
I'm going to update manually then

**Comment by gpion** [comment]
Updated now
But that mean that it was fixed form before switching to 1.3.2b0  ?

**Comment by gpion** [comment]
I've switched to use HACS now . Much simpler for uograding

**Comment by pnbruckner** [comment]
It is a race condition, which means it is very timing sensitive, and therefore intermittent. When I first tried to reproduce the problem I couldn't. Even once I was able to, it would only happen every 5 to 10 restarts.

**Comment by gpion** [comment]
> go to the HACS page, click on Google Maps, and it should show you which version is installed. You can also use the three-dot menu in the top-right to install a different version.
It stills show 1.3.1 : 
![image](https://github.com/pnbruckner/ha-google-maps/assets/2971216/586f95da-c863-45fb-b273-7cbe87aee27b)

**Comment by pnbruckner** [comment]
Click on Update Information, then click on Redownload. You may have to enable beta versions to be shown.

**Comment by gpion** [comment]
"redownload" was needed 
![image](https://github.com/pnbruckner/ha-google-maps/assets/2971216/6d65cd4e-3965-413a-a256-a305faf477b7)

**Comment by prndlrm** [comment]
> @prndlrm & @gpion, please try 1.3.2b0 and let me know if it resolves the problem for you.

I've restarted 5 times with 1.3.2b0 and it has 100% passed, entities always show up.

For the 8-12 times I restarted in the prior 48 hours with 1.3.1 and 1.3.0 I was losing the entities 100% of the time.

Nice work, everything looks fine with this version so far.

**Comment by dwolko** [comment]
Same issue from past few days.
Testing 1.3.2b0 and everything looks fine.
Good work!

**Comment by pnbruckner** [comment]
Found a better implementation I've tested with GPSLogger, so I'll change the implementation of the fix here, too.

**Comment by dwolko** [comment]
In my testing, GPSLogger drain battery faster than Google Maps

**Comment by gpion** [comment]
> > @prndlrm & @gpion, please try 1.3.2b0 and let me know if it resolves the problem for you.
> 


The issue was apparently already solved for me.
Now I've switched and its still OK (fortunately )

**Comment by pnbruckner** [comment]
Another update...

I found out why sometimes the entity registry entries get removed instead of just being updated.

When the device tracker component decides to delete devices from the device registry, it first disassociates the corresponding entity registry entries from the device before deleting the device from the device registry. This _should_ prevent the entity registry entries from being deleted.

The entity registry listens for devices being deleted from the device registry. When a device is deleted, it checks to see if any entities are associated with that device. If so, it will delete those entities from itself (i.e., the entity registry.) Since the entities were "unlinked" from the device, they _shouldn't_ get deleted.

HOWEVER, there is a delay between when the device is removed from the device registry and when the entity registry responds to that event. If, in the meantime, the entity is updated (again) to link to the device (and the device is re-created), by the time the entity registry tries to process the device removal, it will see entities associated with the device, _and will remove them!_

This happens if an integration is creating its device tracker entities during this short time window, which _does_ happen, and is ultimately the reason behind the problem first described in this issue.

Turns out, that delay has already been fixed, and will be in the 2024.4 release. (See https://github.com/home-assistant/core/pull/113623.) I'm also probably submit a PR to remove that old code from the device tracker component, as discussed in that referenced PR. Unfortunately, though, that doesn't solve the problem for people using older HA versions. So, this integration still needs a work around.

The existing work around (in 1.3.2b1) should be good enough, or at least, for most cases.

However, I'm now considering removing the work around and adding a binary sensor instead. I never liked the idea that an entity should become unavailable when its source (the server, in this case) becomes unavailable. IMHO, that state information should be provided "out of band" (i.e., in a separate sensor or attribute.) After all, any entity that is based on sampling (which pretty much all are) just represents the last known value, and that should continue to be true no matter how far it is between good samples. So, instead of the device tracker becoming unavailable, I'll have a separate binary sensor that indicates if the server is available or not. That way, if you don't care, you'll still see the last known good location, and if you do care, you can do something (via an automation or something) if/when either last_seen becomes too stale, and/or the binary "connected" sensor turns off.
