### ISSUE TITLE
Refresh cookies

### ISSUE THREAD

**Issue by carefulcomputer** [pnbruckner/ha-google-maps#8]
Thank you for giving TLC to google map location feature of HA. It had been so much problematic in past. Almost all of the problems are related to cookies expiring. When google cookies expire they sent new set of cookies so user doesn't have to log in again. In current implementation of HA google map feature there is no way to fetch the new set of cookies and hence the problems.
However, the [author of locationsharinglib has indicated that the library may have access to the new cookies](https://github.com/costastf/locationsharinglib/issues/110#issuecomment-1681645246). However since it is just a library, it doesn't know where to store the new cookies. 
One way to solve the cookies renewal problem could be for library to allow a callback to be registered whenever new cookies are received.
With that functionality, your map locator could use the callback to store the new cookies whenever locationsharinglib gets new set. 
Of course, this will require locationsharinglib's author's help. @costastf
WDYT ?

**Comment by pnbruckner** [comment]
I think I did see a discussion about that. But, yes, if something like that was implemented, I'd be happy to use it in my custom version of the HA Google Maps integration.

**Comment by costastf** [comment]
In the early days of locationsharinglib the cookies were retrieved automatically. Pretty soon, after people from all over the world started using it, it became very clear that google has different authentication settings around the world. Later it was semi automated but that was still not working for all and then I ended up having this approach with the cookies provided by the user. Please keep in mind about this because anything that might work for you might not work for another person in another person somewhere else in the world due to google inconsistencies. This is what makes this hard ;)

**Comment by carefulcomputer** [comment]
yup, google has an habit of changing their auth method/cookies. been burnt few times when i had Asterisk voip sever which used google voice integration. :) 
For this case, I think as long as locationsharing lib calls the callback with new cookies, the caller can choose how to handle them in an way they want.  in worst case situation, caller completely ignores the callback and just uses the manual set of cookies.

**Comment by pnbruckner** [comment]
@costastf if you've been following the work I've been doing on the HA Google Maps integration, you may have seen that I had created a subclass of your locationsharinglib Service class to enhance its error checking & reporting, cookie management, etc. If not, I wanted to let you know I've now rewritten the class to be more in line with my use of it. The changes were starting to get too extensive, and I didn't think they would be compatible with other users of your package, which is why I didn't try to submit a PR. But feel free to use in your package any of what I've done here. You can see the current state at https://github.com/pnbruckner/ha-google-maps/blob/misc/custom_components/google_maps/gm_loc_sharing.py. At some point I may create a new pypi.org package based on it (if/when I submit any of this back to the HA code base.)

**Comment by costastf** [comment]
Hi @pnbruckner , i have followed the work you are doing, it's awesome! I completely understand the choice you made and either way is fine by me. I do think that we could integrate your changes to the existing library and keep this (changing some naming choices ;) but if you want to be more flexible owning the code and being able to change and release at will, i completely understand. The intend of the library was for integration with HA and since you have done such a great work it might not be relevant any more, not sure tbh, because i think that people are using it independently. We can go forward any way you prefer. 👍
